-- supabase/migrations/20260709180000_seed_base_artifacts.sql
-- Seeds the 12 base artifacts that the old Supabase project had inserted
-- manually. Must run before 20260709184656 (unique_quest_templates FK).

INSERT INTO public.artifacts (id, category, name_bm, name_en, description_bm, description_en, era_bm, era_en, origin_bm, origin_en, material_bm, material_en, icon, sort_order) VALUES
('keris-panjang','weapons','Keris Panjang','Long Keris',
 'Keris panjang ialah senjata upacara diraja dengan bilah bergelombang, lambang kedaulatan dan keberanian pahlawan Melayu.',
 'The long keris is a royal ceremonial weapon with a wavy blade, symbolising sovereignty and the courage of Malay warriors.',
 'Abad ke-15','15th century','Kesultanan Melayu','Malay Sultanates','Besi tempaan dan kayu','Forged iron and wood','sword',1),
('meriam-melaka','weapons','Meriam Melaka','Malacca Cannon',
 'Meriam tembaga yang digunakan untuk mempertahankan Kota Melaka, menggambarkan kepakaran tempaan logam zaman kesultanan.',
 'A bronze cannon used to defend the fortress of Malacca, reflecting the metal-forging expertise of the sultanate era.',
 'Abad ke-15 hingga ke-16','15th to 16th century','Melaka','Malacca','Tembaga','Bronze','sword',2),
('terabai','weapons','Terabai','Terabai Shield',
 'Perisai kayu tradisional kaum Iban dan Bidayuh, dihiasi ukiran motif haiwan dan roh pelindung.',
 'A traditional wooden shield of the Iban and Bidayuh peoples, adorned with animal and guardian-spirit motifs.',
 'Abad ke-18 hingga ke-19','18th to 19th century','Sarawak','Sarawak','Kayu keras dan cat asli','Hardwood and natural pigments','shield',3),
('tengkolok','regalia','Tengkolok Diraja','Royal Tengkolok',
 'Ikat kepala rasmi pakaian diraja Melayu, dilipat mengikut gaya negeri masing-masing.',
 'The official Malay royal headdress, folded in styles distinctive to each state.',
 'Abad ke-15 hingga kini','15th century to present','Semenanjung Tanah Melayu','Malay Peninsula','Kain songket','Songket cloth','crown',4),
('baju-kurung-diraja','regalia','Baju Kurung Diraja','Royal Baju Kurung',
 'Pakaian diraja daripada sutera dan songket bersulam benang emas, dipakai dalam istiadat rasmi istana.',
 'Royal attire crafted from silk and songket with gold thread embroidery, worn during formal palace ceremonies.',
 'Abad ke-17 hingga kini','17th century to present','Istana Melayu','Malay palaces','Sutera, songket, benang emas','Silk, songket, gold thread','crown',5),
('set-perak-diraja','regalia','Set Perak Diraja','Royal Silver Set',
 'Set perkakas perak istana termasuk tepak sirih, cerana dan bekas kemenyan.',
 'A palace silverware set including betel-nut caskets, offering trays and incense holders.',
 'Abad ke-18 hingga ke-19','18th to 19th century','Kelantan dan Terengganu','Kelantan and Terengganu','Perak tulen','Pure silver','crown',6),
('gong-gamelan','music','Gong Gamelan','Gamelan Gong',
 'Gong perunggu yang menjadi tulang belakang ensembel gamelan Melayu.',
 'A bronze gong that anchors the Malay gamelan ensemble.',
 'Abad ke-18','18th century','Pahang dan Terengganu','Pahang and Terengganu','Perunggu','Bronze','music',7),
('rebana-ubi','music','Rebana Ubi','Rebana Ubi Drum',
 'Gendang besar berbentuk ubi yang dipalu semasa perayaan di pantai timur.',
 'A large tuber-shaped drum struck during festivals on the east coast.',
 'Abad ke-15 hingga kini','15th century to present','Kelantan','Kelantan','Kayu keras dan kulit lembu','Hardwood and cow hide','music',8),
('seruling-tradisional','music','Seruling Tradisional','Traditional Flute',
 'Seruling buluh yang menghasilkan nada lembut, sering dimainkan dalam Mak Yong dan Wayang Kulit.',
 'A bamboo flute producing gentle tones, often played in Mak Yong and Wayang Kulit performances.',
 'Turun-temurun','Passed down through generations','Semenanjung Tanah Melayu','Malay Peninsula','Buluh','Bamboo','music',9),
('alat-tenun-songket','crafts','Alat Tenun Songket','Songket Loom',
 'Alat tenun kayu tradisional untuk menghasilkan kain songket bersulam benang emas dan perak.',
 'A traditional wooden loom used to weave songket cloth with gold and silver thread.',
 'Abad ke-16 hingga kini','16th century to present','Terengganu dan Kelantan','Terengganu and Kelantan','Kayu, benang sutera dan benang emas','Wood, silk thread and gold thread','archive',10),
('wau-bulan','crafts','Wau Bulan','Moon Kite',
 'Layang-layang tradisional berbentuk bulan sabit dengan hiasan corak halus.',
 'A traditional crescent-moon kite decorated with intricate patterns.',
 'Abad ke-16 hingga kini','16th century to present','Kelantan','Kelantan','Buluh dan kertas berwarna','Bamboo and coloured paper','archive',11),
('canting-batik','crafts','Canting Batik','Batik Canting',
 'Alat kecil bermata tembaga untuk melukis lilin cair pada kain batik.',
 'A small copper-spouted tool used to apply molten wax onto batik cloth.',
 'Abad ke-19 hingga kini','19th century to present','Kelantan dan Terengganu','Kelantan and Terengganu','Tembaga dan kayu','Copper and wood','archive',12)
ON CONFLICT (id) DO NOTHING;
